#!/usr/bin/env python3
"""Stage-2 per-idea independent meta-review via gpt-5.4 (crisinsjtu proxy).

Each idea is reviewed in complete isolation: the model sees only the baseline
paper method extract + one idea text. Runs all 10 in parallel via asyncio.
"""
import asyncio
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / "Research" / "gptapi"))
from llm_client import get_async_client  # noqa: E402

ROOT = Path("/home/cris/Research/LTSGEN/.research")
IDEAS_RAW = ROOT / "ideas-raw-20260419-2200.md"
CARDS_DIR = ROOT / "idea-cards"
CARDS_DIR.mkdir(exist_ok=True)

BASELINE_EXTRACT = """
BASELINE PAPER: OpenTSLM — Time-Series Language Models for Reasoning over
Multivariate Medical Text- and Time-Series Data (Stanford+ETH+Google+Amazon,
arXiv 2510.02410, 2025-10; code: github.com/StanfordBDHG/OpenTSLM).

Method (faithful extract):
- TS modality integrated as NATIVE in pretrained LLM via two variants:
  (i) OpenTSLM-SoftPrompt: learnable TS tokens concatenated with text tokens
      (implicit TS modeling);
  (ii) OpenTSLM-Flamingo: gated cross-attention over Chronos-2 patch
      embeddings injected into the LLM (explicit modality).
- Three custom Chain-of-Thought datasets: HAR-CoT, Sleep-CoT, ECG-QA-CoT;
  all medical, synthetic CoT traces generated by a stronger LLM.
- Training objective: next-token LM loss on reference CoT traces.
- Headline: 69.9% F1 on sleep staging, 65.4% on HAR, vs 9.05% / 52.2% for
  finetuned text-only models; surpasses GPT-4o.
- Limitations observed by the user's own replication:
  * no ablation of caption utility on external held-out QA;
  * training objective has no mechanism forcing generated caption to
    condition on input TS shape;
  * counterfactual probe (time reversal + variance injection) on user's
    retrained OpenTSLM yields only 2.78% correct-flip rate (i.e., caption
    is essentially input-agnostic template);
  * oracle caption reaches 96-100% on shape-QA but learned caption is 36%
    vs wrong_caption 38% (in-dist and OOD).

Relevant adjacent works the idea MUST differentiate from:
- ChatTS (VLDB 2025, ByteDance, 14B OSS): synthetic Evol-Instruct QA +
  SFT; +46% alignment, +25.8% reasoning over GPT-4o.
- CapRL (ICLR 2026, InternLM): VLM caption → vision-free LLM answers MCQ →
  accuracy-as-RL-reward. Current SOTA paradigm for VLM captioning. NOT yet
  applied to time series.
- TimeMaster (2506.13705): Qwen2.5-VL-3B + SFT + GRPO with composite
  reward (format + classification accuracy + LLM-judged insight).
  Does NOT use decoupled QA-probe as reward.
- TS-CLIP (EMNLP 2025): contrastive TS-text with synonym bank to fight
  label collapse; does not generate text.
- TimeART (2601.13653): agentic TSQA with 21 tools.
- TRQA (OpenReview ULQt51DRug): 6-task TS reasoning benchmark.
"""

REVIEW_PROMPT = """You are a strict, skeptical meta-reviewer at a top ML venue
(NeurIPS / ICML / ICLR / EMNLP main track). You default to REJECT; most
submitted ideas are rejected. You are evaluating a PhD student's candidate
research idea after their pilot experiment indicated the mainstream approach
fails. You must be critical and specific; vague praise is unacceptable.

{baseline}

CANDIDATE IDEA (sole target of this review, evaluated in full isolation from
any other candidate):

{idea}

Evaluate on these dimensions, scoring each 1-5 with a one-sentence
justification:

1. Novelty — is the core claim genuinely new vs the listed adjacent works?
   A 5 means you cannot name a published paper doing this; a 1 means it is a
   direct replication of an existing work.
2. Technical feasibility — can this be built end-to-end by one PhD student
   with 4xA100 + 8x3090 in 2-3 months?
3. Baseline compatibility — does it naturally extend the OpenTSLM stack the
   user already has, or would require a rewrite?
4. Implementation complexity (1 = trivial, 5 = PhD-thesis scale — LOWER IS
   BETTER for feasibility but HIGHER can mean more substantial contribution).
5. Expected improvement magnitude — 1 = marginal, 5 = transformative.
6. Risk of being scooped in the next 6 months — 1 = unlikely, 5 = someone
   probably already has a preprint.

Then produce a final verdict:
- GO: strong idea, pursue as-is
- REVISE: core is sound but needs sharpening; specify exactly what
- KILL: fundamental problem; specify the failure mode

Also answer, in 2-3 sentences each:
- What is the strongest reason a reviewer at ICLR 2027 / NeurIPS 2026 would
  REJECT this paper?
- What is the single most load-bearing empirical result that must work for
  this paper to succeed?
- Name any specific recent (2024-2026) paper that is dangerously similar and
  that the user must differentiate from.

Output format: well-formed markdown idea card with headings
'## Scores', '## Final verdict', '## Weaknesses', '## Load-bearing result',
'## Prior-art collision risk'. Do NOT include the raw idea text in your
output.
"""


def split_ideas(text: str) -> list[tuple[int, str]]:
    """Return list of (idea_number, idea_text) from raw output."""
    pattern = re.compile(r"(### Idea (\d+):[\s\S]+?)(?=\n### Idea \d+:|\Z)")
    out = []
    for m in pattern.finditer(text):
        num = int(m.group(2))
        body = m.group(1).strip()
        out.append((num, body))
    return out


async def review_one(client, num: int, idea_text: str) -> None:
    prompt = REVIEW_PROMPT.format(baseline=BASELINE_EXTRACT, idea=idea_text)
    resp = await client.chat.completions.create(
        model="gpt-5.4",
        messages=[{"role": "user", "content": prompt}],
    )
    card = resp.choices[0].message.content
    out_path = CARDS_DIR / f"idea-{num:02d}-card.md"
    header = f"# Review Card — Idea {num}\n\n_Reviewed by gpt-5.4, single-idea isolation._\n\n"
    out_path.write_text(header + card + "\n")
    print(f"[done] idea {num:02d} -> {out_path.name} ({len(card)} chars)", flush=True)


async def main():
    raw = IDEAS_RAW.read_text()
    ideas = split_ideas(raw)
    if len(ideas) != 10:
        print(f"WARNING: found {len(ideas)} ideas, expected 10", file=sys.stderr)
        for n, _ in ideas:
            print(f"  found idea {n}", file=sys.stderr)
    client = get_async_client()
    await asyncio.gather(*(review_one(client, n, t) for n, t in ideas))


if __name__ == "__main__":
    asyncio.run(main())
